SRCS += $(wildcard $(PLATFORM_DIR)/*.c)

CC = gcc
CFLAGS = -Wall -Werror -pedantic -O2 -fPIC -I$(HEADS_DIR)
LDFLAGS =

IMG  ?= 
ARGS ?= 

OBJS = $(patsubst %.c, build/%.o, $(SRCS))
LIB_NAME = lib$(PROJECT_NAME).so

$(LIB_NAME): $(OBJS)
	@echo "[LINK] Linking dynamic library: $(LIB_NAME)"
	@$(CC) -shared -o $(LIB_NAME) $^ $(LDFLAGS)

build/%.o: %.c $(HEADS)
	@echo "[CC] Compiling $< -> $@"
	@mkdir -p $(dir $@)  
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@echo "[CLEAN] Cleaning up build artifacts"
	@rm -f $(PROJECT_NAME) $(LIB_NAME) $(OBJS)
	@rm -rf build

.PHONY: clean run
